// Generated by gir (https://github.com/gtk-rs/gir @ 0e476ab5c1de)
// from ../.. (@ 69236eb3bf7a+)
// from ../../gir-files (@ cfc0305f903b)
// DO NOT EDIT

#[cfg(not(docsrs))]
use std::process;

#[cfg(docsrs)]
fn main() {} // prevent linking libraries to avoid documentation failure

#[cfg(not(docsrs))]
fn main() {
    if let Err(s) = system_deps::Config::new().probe() {
        println!("cargo:warning={s}");
        process::exit(1);
    }
}
