// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use glib::{prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_};

glib::wrapper! {
    #[doc(alias = "PhoshLockscreen")]
    pub struct Lockscreen(Object<ffi::PhoshLockscreen, ffi::PhoshLockscreenClass>);

    match fn {
        type_ => || ffi::phosh_lockscreen_get_type(),
    }
}

impl Lockscreen {
    //#[doc(alias = "phosh_lockscreen_new")]
    //pub fn new(layer_shell: /*Unimplemented*/Option<Basic: Pointer>, wl_output: /*Unimplemented*/Option<Basic: Pointer>, calls_manager: /*Ignored*/&CallsManager) -> Lockscreen {
    //    unsafe { TODO: call ffi:phosh_lockscreen_new() }
    //}

            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`Lockscreen`] objects.
            ///
            /// This method returns an instance of [`LockscreenBuilder`](crate::builders::LockscreenBuilder) which can be used to create [`Lockscreen`] objects.
            pub fn builder() -> LockscreenBuilder {
                LockscreenBuilder::new()
            }
        

    //#[doc(alias = "phosh_lockscreen_get_page")]
    //#[doc(alias = "get_page")]
    //pub fn page(&self) -> /*Ignored*/LockscreenPage {
    //    unsafe { TODO: call ffi:phosh_lockscreen_get_page() }
    //}

    //#[doc(alias = "phosh_lockscreen_set_page")]
    //pub fn set_page(&self, page: /*Ignored*/LockscreenPage) {
    //    unsafe { TODO: call ffi:phosh_lockscreen_set_page() }
    //}

    //#[doc(alias = "calls-manager")]
    //pub fn calls_manager(&self) -> /*Ignored*/Option<CallsManager> {
    //    ObjectExt::property(self, "calls-manager")
    //}

    #[doc(alias = "lockscreen-unlock")]
    pub fn connect_lockscreen_unlock<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn lockscreen_unlock_trampoline<F: Fn(&Lockscreen) + 'static>(this: *mut ffi::PhoshLockscreen, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"lockscreen-unlock\0".as_ptr() as *const _,
                Some(std::mem::transmute::<_, unsafe extern "C" fn()>(lockscreen_unlock_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "wakeup-output")]
    pub fn connect_wakeup_output<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn wakeup_output_trampoline<F: Fn(&Lockscreen) + 'static>(this: *mut ffi::PhoshLockscreen, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"wakeup-output\0".as_ptr() as *const _,
                Some(std::mem::transmute::<_, unsafe extern "C" fn()>(wakeup_output_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }
}

impl Default for Lockscreen {
                     fn default() -> Self {
                         glib::object::Object::new::<Self>()
                     }
                 }

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`Lockscreen`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct LockscreenBuilder {
            builder: glib::object::ObjectBuilder<'static, Lockscreen>,
        }

        impl LockscreenBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            //pub fn calls_manager(self, calls_manager: /*Ignored*/&CallsManager) -> Self {
                        //    Self { builder: self.builder.property("calls-manager", calls_manager), }
                        //}

    // rustdoc-stripper-ignore-next
    /// Build the [`Lockscreen`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> Lockscreen {
    self.builder.build() }
}
