// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use glib::{translate::*};

glib::wrapper! {
    #[doc(alias = "PhoshScreenshotManager")]
    pub struct ScreenshotManager(Object<ffi::PhoshScreenshotManager, ffi::PhoshScreenshotManagerClass>);

    match fn {
        type_ => || ffi::phosh_screenshot_manager_get_type(),
    }
}

impl ScreenshotManager {
    #[doc(alias = "phosh_screenshot_manager_new")]
    pub fn new() -> ScreenshotManager {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::phosh_screenshot_manager_new())
        }
    }

    //#[doc(alias = "phosh_screenshot_manager_do_screenshot")]
    //pub fn do_screenshot(&self, area: /*Ignored*/&gdk::Rectangle, filename: &str, include_cursor: bool) -> bool {
    //    unsafe { TODO: call ffi:phosh_screenshot_manager_do_screenshot() }
    //}
}

impl Default for ScreenshotManager {
                     fn default() -> Self {
                         Self::new()
                     }
                 }
